Panfrost drm WIP
evadot/drm-subtree pull request #3
Opened 2021-02-24 22:42 UTC by bukinr

All of these is needed for Panfrost driver operation with Mali T860 GPU.
Some changes are memory leak fixes.
I'm able to run sway and browsers (drm_kqfilter is needed for sway).
The Mali T860 has three hardware threads, so DRM scheduler is ported from Linux.
It works well with no memory or file destriptor leakages.
demo: https://twitter.com/onewilshire/status/1363792441871073280

2021-02-26 08:36 UTC, evadot commented
Just a question before I start reading code, from which Linux version the scheduler have been taken ?
Currently this repo is synced with 5.6

2021-02-26 12:37 UTC, bukinr commented
> Just a question before I start reading code, from which Linux version the scheduler have been taken ?
> Currently this repo is synced with 5.6
From linux master as of Nov-Dec 2020 I think, but I can sync with latest master or any branch

2021-02-26 12:45 UTC, evadot commented
> > Just a question before I start reading code, from which Linux version the scheduler have been taken ?
> > Currently this repo is synced with 5.6
> 
> From linux master as of Nov-Dec 2020 I think, but I can sync with latest master or any branch

Ok, well if that works with what's in 5.6 that would ease future update to use that.

2021-03-22 10:52 UTC, evadot requested changes

2021-03-22 10:52 UTC, evadot commented on core/include/drm/drm_file.h
> +	struct selinfo	drm_rsel;
Can you add some ifdef #FreeBSD here ?

2021-03-22 10:52 UTC, evadot commented on core/include/drm/drm_file.h
> +int drm_kqfilter(struct file *filp, struct knote *kn);
Same here

2021-03-22 10:52 UTC, evadot commented on drmkpi/include/drmkpi/fs.h
> +	int (*kqfilter)(struct file *, struct knote *);
And here

2021-03-22 19:13 UTC, bukinr commented on core/include/drm/drm_file.h
> +	struct selinfo	drm_rsel;
Added

2021-03-22 19:13 UTC, bukinr commented on core/include/drm/drm_file.h
> +int drm_kqfilter(struct file *filp, struct knote *kn);
Added

2021-03-22 19:13 UTC, bukinr commented on drmkpi/include/drmkpi/fs.h
> +	int (*kqfilter)(struct file *, struct knote *);
Added

2021-07-20 14:44 UTC, bukinr commented
rework needed

2021-07-20 14:44 UTC, closed without merging